{
 "title": "Database Connection Pool",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Pool Timed Out",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "delta(jboss_datasources_pool_timed_out[$__interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Entity Cache Count",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "jboss_infinispan_number_of_entries{cache_container=\"hibernate\", cache=\"cache-wisely.war#default.com.redhat.consulting.cache.wisely.Item\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Pooled DB Connections",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "jboss_datasources_pool_active_count{data_source=\"cachestore\"}",
     "legendFormat": "{{instance}}-active"
    },
    {
     "expr": "jboss_datasources_pool_available_count{data_source=\"cachestore\"}",
     "legendFormat": "{{instance}}-available"
    }
   ]
  }
 ]
}