{
 "title": "Linux OS",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Dropped Packets",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_drop_total{device!=\"lo\"}[$__rate_interval])",
     "legendFormat": "{{instance}}-{{device}}-rx"
    },
    {
     "expr": "rate(node_network_transmit_drop_total{device!=\"lo\"}[$__rate_interval])",
     "legendFormat": "{{instance}}-{{device}}-tx"
    }
   ]
  },
  {
   "title": "Huge Pages",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 8, "x": 8, "y": 0 },
   "targets": [
    { "expr": "node_memory_HugePages_Total", "legendFormat": "{{instance}}-total" },
    { "expr": "node_memory_HugePages_Free", "legendFormat": "{{instance}}-free" }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "node_memory_MemFree_bytes", "legendFormat": "{{instance}}-free" },
    { "expr": "node_memory_MemTotal_bytes", "legendFormat": "{{instance}}-total" }
   ]
  }
 ]
}