{
 "title": "Linux SNMP",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "RAM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "targets": [
    {
     "expr": "hrStorageUsed{hrStorageIndex=\"1\"}",
     "legendFormat": "{{instance}}-used"
    },
    {
     "expr": "hrStorageSize{hrStorageIndex=\"1\"}",
     "legendFormat": "{{instance}}-total"
    }
   ]
  },
  {
   "title": "Swap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "targets": [
    {
     "expr": "hrStorageUsed{hrStorageIndex=\"3\"}",
     "legendFormat": "{{instance}}-used"
    },
    {
     "expr": "hrStorageSize{hrStorageIndex=\"3\"}",
     "legendFormat": "{{instance}}-total"
    }
   ]
  },
  {
   "title": "In-Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(ifInErrors{ifDescr!=\"lo\"}[$__rate_interval])",
     "legendFormat": "{{instance}}-{{ifDescr}}"
    }
   ]
  },
  {
   "title": "Out-Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(ifOutErrors{ifDescr!=\"lo\"}[$__rate_interval])",
     "legendFormat": "{{instance}}-{{ifDescr}}"
    }
   ]
  },
  {
   "title": "In-Discards",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(ifInDiscards{ifDescr!=\"lo\"}[$__rate_interval])",
     "legendFormat": "{{instance}}-{{ifDescr}}"
    }
   ]
  },
  {
   "title": "Out-Discards",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(ifOutDiscards{ifDescr!=\"lo\"}[$__rate_interval])",
     "legendFormat": "{{instance}}-{{ifDescr}}"
    }
   ]
  }
 ]
}